{% set name = "cbflib" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Temporarily use git repository until we figure out what changes are
  # needed. Then coordinate with @yayahjb to make a new release.
  # url: https://github.com/yayahjb/cbflib/archive/CBFlib-{{ version }}.tar.gz
  # sha256: b3ed6cbddc7dd9c565ac116a6eaf44a437e88808921a4e458a26e327e3f66f48
  - git_url: https://github.com/ndevenish/cbflib
    git_rev: refactor

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # - {{ compiler('fortran') }}  # [not win]
    - python
    - cmake
    - swig
    - ninja  # [not win]
    - m4     # [not win]

  host:
    - python
    - hdf5 <1.12
    - pcre
    - pip

  run:
    - python
    - hdf5 <1.12
    - pcre

test:
  imports:
    - pycbf

about:
  home: https://github.com/yayahjb/cbflib
  license: GPL-2.0-only OR LGPL-2.0-only
  license_family: GPL
  license_file:
    - doc/gpl.txt
    - doc/lgpl.txt
  summary: 'Library for Crystallographic Binary File Dictionary (CBF)'
  description: |
    C and Python library for reading CBF formatted files
  doc_url: https://github.com/yayahjb/cbflib
  dev_url: https://github.com/yayahjb/cbflib

extra:
  recipe-maintainers:
    - Anthchirp
    - bkpoon
    - graeme-winter
    - ndevenish
    - phyy-nx
    - yayahjb
